### PR TITLE
Updated Ember CLI to 3.1.4 + some updated dependencies

### PR DESCRIPTION
**Pull request by tzellman**

### CODE REVIEW

**Comment by lolmaus** [comment]
:heart_eyes:

Thx! I'll find time to try, merge and release this along with the other pending PR.

**Comment by tzellman** [comment]
Hello! Just curious; is there any update on this?

I can also create a separate PR if you'd like to update to a newer release. Thanks!

**Comment by lolmaus** [comment]
> Hello! Just curious; is there any update on this?

Nope. :( Totally slipped away from me.

> I can also create a separate PR if you'd like to update to a newer release. Thanks!

Please do. I'll add it to my todo list and make sure to have it merged and released. :bow:

**Comment by vvainio** [comment]
My apologies for the lack of response on our part. We have just released version 4.0.0 which fixes a bunch of deprecations.

**Pull request closed without merging**
