### PR TITLE
Update to Babel 6 and use New Module Imports

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves https://github.com/workmanw/ember-string-ishtmlsafe-polyfill/issues/5

/cc @lolmaus

### CODE REVIEW

**Comment by Turbo87** [comment]
CI issues seem unrelated and match the issues on the `master` branch

**Comment by lolmaus** [comment]
Thank you so much, @Turbo87!

1. I've updated the `gen-1` branch. The issue was caused by an unlocked dependency. Please merge/rebase to see the tests pass.
2. Where are the new imports documented? I love them, but feel insecure using an undocumented feature.
3. How far are the new imports backward compatible?
4. Is the upgrade to Babel 6 backward compatible?

**Comment by Turbo87** [comment]
> I've updated the gen-1 branch. The issue was caused by an unlocked dependency. Please merge/rebase to see the tests pass.

done

> Where are the new imports documented? I love them, but feel insecure using an undocumented feature.

https://github.com/ember-cli/ember-rfc176-data

> How far are the new imports backward compatible?

they compile down to using the `Ember` global at the moment, so they should be compatible all the way down to Ember v1.0

> Is the upgrade to Babel 6 backward compatible?

yes, each addon is in control of its own transpilation, and addons using Babel 6 still work in apps using Babel 5.

**Comment by lolmaus** [comment]
Thank you. :bowing_man:

**Comment by lolmaus** [comment]
Released as `3.0.2`.

**Pull request merged**
